import axios from 'axios';
import { getDb } from './db.js';

const BASE_URL = 'https://cloud-as.ruijienetworks.com';

let accessToken = null;
let tokenExpiresAt = 0;

// Lấy Token xác thực từ Ruijie
export async function getAccessToken() {
    // Tái sử dụng token nếu chưa hết hạn
    if (accessToken && Date.now() < tokenExpiresAt) {
        return accessToken;
    }

    try {
        const db = getDb();
        const APP_ID = db.ruijie.appId || 'openb79f8985c8dd';
        const APP_SECRET = db.ruijie.appSecret || '65a7761ef24f4cde84302d348850ba25';
        const TOKEN_STATIC = db.ruijie.tokenStatic || 'd63dss0a81e4415a889ac5b78fsc904a';

        console.log('[Ruijie API] Đang kết nối để lấy Token...');
        const response = await axios.post(`${BASE_URL}/service/api/oauth20/client/access_token?token=${TOKEN_STATIC}`, {
            appid: APP_ID,
            secret: APP_SECRET
        });
        
        if (response.data && response.data.code === 0 && response.data.accessToken) {
            accessToken = response.data.accessToken;
            // Token mặc định sống 30 ngày, ta set expire sớm hơn 1 chút (ví dụ 1 ngày) để an toàn
            tokenExpiresAt = Date.now() + 24 * 60 * 60 * 1000;
            console.log('[Ruijie API] Lấy Token thành công!');
            return accessToken;
        }
        throw new Error('Phản hồi API lấy Token lỗi: ' + JSON.stringify(response.data));
    } catch (error) {
        console.error('[Ruijie API Lỗi lấy token]:', error.message);
        throw error;
    }
}

// Lấy danh sách Network Groups
export async function getNetworkGroups() {
    const token = await getAccessToken();
    try {
        const response = await axios.get(`${BASE_URL}/service/api/group/single/tree?depth=BUILDING&access_token=${token}`);
        if (response.data && response.data.code === 0) {
            return response.data.groups; // Trả về danh sách Group
        }
        throw new Error('Lỗi lấy Network Groups: ' + JSON.stringify(response.data));
    } catch (error) {
        console.error('[Ruijie API Lỗi lấy Network Groups]:', error.message);
        throw error;
    }
}

// Lấy danh sách User Groups (Gói cước / Băng thông)
export async function getUserGroups(groupId) {
    const token = await getAccessToken();
    try {
        // API: [CloudUrlPrefix]/service/api/intl/usergroup/list/{group_Id}?pageIndex={start}&pageSize={pageSize}&access_token={}
        const response = await axios.get(`${BASE_URL}/service/api/intl/usergroup/list/${groupId}?pageIndex=0&pageSize=100&access_token=${token}`);
        if (response.data && response.data.code === 0) {
            return response.data.data; // Trả về mảng các gói
        }
        throw new Error('Lỗi lấy User Groups: ' + JSON.stringify(response.data));
    } catch (error) {
        console.error('[Ruijie API Lỗi lấy User Groups]:', error.message);
        throw error;
    }
}

// Tạo 1 Voucher mới dựa trên groupId và userGroupId (gói cước)
export async function generateVoucher(groupId, userGroupId, profileId) {
    const token = await getAccessToken();
    try {
        console.log(`[Ruijie API] Đang tạo Voucher cho gói ${userGroupId}...`);
        const payload = {
            quantity: 1,
            profile: profileId,
            userGroupId: parseInt(userGroupId, 10),
            comment: 'Auto-generated by Vali Portal'
        };
        const response = await axios.post(`${BASE_URL}/service/api/open/auth/voucher/create/${groupId}?access_token=${token}`, payload);
        
        if (response.data && response.data.code === 0) {
            // response.data.voucherData.list
            const voucherList = response.data.voucherData?.list || response.data['List Price'] || response.data.data || response.data.result;
            if (voucherList && voucherList.length > 0) {
                const voucherCode = voucherList[0].codeNo;
                console.log(`[Ruijie API] Đã tạo thành công Voucher: ${voucherCode}`);
                return voucherCode;
            }
        }
        throw new Error('Lỗi tạo Voucher: ' + JSON.stringify(response.data));
    } catch (error) {
        console.error('[Ruijie API Lỗi tạo Voucher]:', error.response ? error.response.data : error.message);
        throw error;
    }
}

// Gửi Voucher lên portal-as để kích hoạt mạng cho thiết bị
export async function submitVoucherToPortal(sessionId, voucherCode) {
    try {
        const payload = {
            lang: 'vi',
            authType: 'voucher',
            sessionId: sessionId,
            account: voucherCode
        };
        const response = await axios.post('https://portal-as.ruijienetworks.com/api/auth/general', payload);
        console.log('[Ruijie API Portal Logon]:', response.data);
        return response.data; // { success: true, result: { logonUrl: '...' } }
    } catch (error) {
        console.error('[Ruijie API Lỗi Portal Logon]:', error.response ? error.response.data : error.message);
        throw error;
    }
}

// Cấp quyền truy cập WiFi gói Free
export async function authorizeFreeWiFi(macAddress) {
    // Lưu ý: Các ID này sau này sẽ lấy từ .env hoặc lấy ID của gói "Free" sau khi debug
    // Hàm này tạm thời chưa chạy thực vì chưa biết ID chính xác
    return { success: true, message: 'Đã mở khóa truy cập mạng ở mức Free', isMock: true };
}

// Nâng cấp băng thông gói VIP (100Mbps)
export async function upgradeToVIP(macAddress) {
    return { success: true, message: 'Đã nâng cấp lên gói VIP thành công', isMock: true };
}
